//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_randomizer_SoC.Language {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_local2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_local2() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Simple_randomizer_SoC.Language.en_local2", typeof(en_local2).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string aboutTab {
            get {
                return ResourceManager.GetString("aboutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional parameters.
        /// </summary>
        internal static string additionalTab {
            get {
                return ResourceManager.GetString("additionalTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional parameters.
        /// </summary>
        internal static string additionalTitle {
            get {
                return ResourceManager.GetString("additionalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add the parameter.
        /// </summary>
        internal static string addParameterDialog {
            get {
                return ResourceManager.GetString("addParameterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cartridges.
        /// </summary>
        internal static string ammo {
            get {
                return ResourceManager.GetString("ammo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity per pack.
        /// </summary>
        internal static string ammoBoxCount {
            get {
                return ResourceManager.GetString("ammoBoxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated cartridge parameters.
        /// </summary>
        internal static string ammoParams {
            get {
                return ResourceManager.GetString("ammoParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cartridge parameters.
        /// </summary>
        internal static string ammoParamsShort {
            get {
                return ResourceManager.GetString("ammoParamsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each parameter of cartridges.
        /// </summary>
        internal static string ammoProbability {
            get {
                return ResourceManager.GetString("ammoProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating cartridge parameters.
        /// </summary>
        internal static string ammoSections {
            get {
                return ResourceManager.GetString("ammoSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cartridge sections.
        /// </summary>
        internal static string ammoSectionsShort {
            get {
                return ResourceManager.GetString("ammoSectionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of cartridges.
        /// </summary>
        internal static string ammoType {
            get {
                return ResourceManager.GetString("ammoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor.
        /// </summary>
        internal static string armor {
            get {
                return ResourceManager.GetString("armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating armor parameters.
        /// </summary>
        internal static string armorGenerateSections {
            get {
                return ResourceManager.GetString("armorGenerateSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated armor wear parameters.
        /// </summary>
        internal static string armorImmunityParams {
            get {
                return ResourceManager.GetString("armorImmunityParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor wear parameters.
        /// </summary>
        internal static string armorImmunityParamsShort {
            get {
                return ResourceManager.GetString("armorImmunityParamsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating armor wear parameters.
        /// </summary>
        internal static string armorImmunitySections {
            get {
                return ResourceManager.GetString("armorImmunitySections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor wear sections.
        /// </summary>
        internal static string armorImmunitySectionsShort {
            get {
                return ResourceManager.GetString("armorImmunitySectionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated armor parameters.
        /// </summary>
        internal static string armorMainParams {
            get {
                return ResourceManager.GetString("armorMainParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor parameters.
        /// </summary>
        internal static string armorParams {
            get {
                return ResourceManager.GetString("armorParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each armor parameter.
        /// </summary>
        internal static string armorProbability {
            get {
                return ResourceManager.GetString("armorProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the armor data file.
        /// </summary>
        internal static string armorReadError {
            get {
                return ResourceManager.GetString("armorReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Armor sections.
        /// </summary>
        internal static string armorSections {
            get {
                return ResourceManager.GetString("armorSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Artifact.
        /// </summary>
        internal static string artefact {
            get {
                return ResourceManager.GetString("artefact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Artifacts.
        /// </summary>
        internal static string artefacts {
            get {
                return ResourceManager.GetString("artefacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating artifact parameters.
        /// </summary>
        internal static string artefactsGenerateSection {
            get {
                return ResourceManager.GetString("artefactsGenerateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters with a base value of 0.0.
        /// </summary>
        internal static string artefactsParams0 {
            get {
                return ResourceManager.GetString("artefactsParams0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters of artifact characteristics with a base value of 0.0.
        /// </summary>
        internal static string artefactsParams0Full {
            get {
                return ResourceManager.GetString("artefactsParams0Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters with a base value of 1.0.
        /// </summary>
        internal static string artefactsParams1 {
            get {
                return ResourceManager.GetString("artefactsParams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters of artifact characteristics with a base value of 1.0.
        /// </summary>
        internal static string artefactsParams1Full {
            get {
                return ResourceManager.GetString("artefactsParams1Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each artifact parameter.
        /// </summary>
        internal static string artefactsProbability {
            get {
                return ResourceManager.GetString("artefactsProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the artifact data file.
        /// </summary>
        internal static string artefactsReadError {
            get {
                return ResourceManager.GetString("artefactsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Artifact sections.
        /// </summary>
        internal static string artefactsSections {
            get {
                return ResourceManager.GetString("artefactsSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard generated artifact parameters.
        /// </summary>
        internal static string artefactsStandardParams {
            get {
                return ResourceManager.GetString("artefactsStandardParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Standard artifact parameters.
        /// </summary>
        internal static string artefactsStandardParamsShort {
            get {
                return ResourceManager.GetString("artefactsStandardParamsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated parameters of artifact characteristics.
        /// </summary>
        internal static string artefcatsStats {
            get {
                return ResourceManager.GetString("artefcatsStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace the game text with the one sent by the translator through 10 languages (Russian only).
        /// </summary>
        internal static string brokenTranslate {
            get {
                return ResourceManager.GetString("brokenTranslate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of replacing each text block.
        /// </summary>
        internal static string brokenTranslateProbability {
            get {
                return ResourceManager.GetString("brokenTranslateProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The multiplier of the player&apos;s purchase price.
        /// </summary>
        internal static string buyMultiplier {
            get {
                return ResourceManager.GetString("buyMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player&apos;s purchase price multiplier sections.
        /// </summary>
        internal static string buyMultiplierSections {
            get {
                return ResourceManager.GetString("buyMultiplierSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collections must have the same size.
        /// </summary>
        internal static string collectionsMustHaveSameSize {
            get {
                return ResourceManager.GetString("collectionsMustHaveSameSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Community.
        /// </summary>
        internal static string community {
            get {
                return ResourceManager.GetString("community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consumables.
        /// </summary>
        internal static string consumables {
            get {
                return ResourceManager.GetString("consumables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating consumables parameters.
        /// </summary>
        internal static string consumablesGenerateSections {
            get {
                return ResourceManager.GetString("consumablesGenerateSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated parameters of consumables.
        /// </summary>
        internal static string consumablesParams {
            get {
                return ResourceManager.GetString("consumablesParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consumables parameters.
        /// </summary>
        internal static string consumablesParamsShort {
            get {
                return ResourceManager.GetString("consumablesParamsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each parameter of consumables.
        /// </summary>
        internal static string consumablesProbability {
            get {
                return ResourceManager.GetString("consumablesProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the file with data on consumables.
        /// </summary>
        internal static string consumablesReadError {
            get {
                return ResourceManager.GetString("consumablesReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Consumables sections.
        /// </summary>
        internal static string consumablesSections {
            get {
                return ResourceManager.GetString("consumablesSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters to be copied.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The parameter whose value will be copied.
        /// </summary>
        internal static string copyFromName {
            get {
                return ResourceManager.GetString("copyFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters to be copied.
        /// </summary>
        internal static string copyParams {
            get {
                return ResourceManager.GetString("copyParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all fields of the parameters for copying are filled in correctly.
        /// </summary>
        internal static string copyValidationError {
            get {
                return ResourceManager.GetString("copyValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The amount depends on the difficulty level.
        /// </summary>
        internal static string countByDifficulty {
            get {
                return ResourceManager.GetString("countByDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The number of parameter values cannot be less than 0.
        /// </summary>
        internal static string countCantBeLessThen0 {
            get {
                return ResourceManager.GetString("countCantBeLessThen0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections on the number and probability of occurrence.
        /// </summary>
        internal static string countProbabilitySections {
            get {
                return ResourceManager.GetString("countProbabilitySections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fixed some game crashes due to NPC manipulation (_g.script, xr_statistic.script).
        /// </summary>
        internal static string crashFix {
            get {
                return ResourceManager.GetString("crashFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters with several different types of values.
        /// </summary>
        internal static string CustomList {
            get {
                return ResourceManager.GetString("CustomList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data loading error.
        /// </summary>
        internal static string dataLoadError {
            get {
                return ResourceManager.GetString("dataLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bullets of the killed NPC.
        /// </summary>
        internal static string deadNpcAmmo {
            get {
                return ResourceManager.GetString("deadNpcAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items in the dead NPC&apos;s backpack: .
        /// </summary>
        internal static string deadNpcItems {
            get {
                return ResourceManager.GetString("deadNpcItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items of the killed NPCs.
        /// </summary>
        internal static string deathItemsTab {
            get {
                return ResourceManager.GetString("deathItemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating the presence of each item.
        /// </summary>
        internal static string deathProbability {
            get {
                return ResourceManager.GetString("deathProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings for generating items of killed NPCs.
        /// </summary>
        internal static string deathTitle {
            get {
                return ResourceManager.GetString("deathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excluded actions.
        /// </summary>
        internal static string dialogActionExceptions {
            get {
                return ResourceManager.GetString("dialogActionExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excluded infos.
        /// </summary>
        internal static string dialogInfoExceptions {
            get {
                return ResourceManager.GetString("dialogInfoExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Excluded preconditions.
        /// </summary>
        internal static string dialogPreconditionExceptions {
            get {
                return ResourceManager.GetString("dialogPreconditionExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each dialog.
        /// </summary>
        internal static string dialogProbability {
            get {
                return ResourceManager.GetString("dialogProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dialogues.
        /// </summary>
        internal static string dialogsTab {
            get {
                return ResourceManager.GetString("dialogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dialog generation settings.
        /// </summary>
        internal static string dialogsTitle {
            get {
                return ResourceManager.GetString("dialogsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Difficulty level.
        /// </summary>
        internal static string difficultyLevel {
            get {
                return ResourceManager.GetString("difficultyLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable the alarm in the Bar when an NPC is killed by a player.
        /// </summary>
        internal static string disableBarAlarm {
            get {
                return ResourceManager.GetString("disableBarAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable the automatic deterioration of relations with Freedom when there are NPCs hostile to the player on their base.
        /// </summary>
        internal static string disableFreedomAngry {
            get {
                return ResourceManager.GetString("disableFreedomAngry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disable automatic weapon removal in some places.
        /// </summary>
        internal static string disableHidingWeapons {
            get {
                return ResourceManager.GetString("disableHidingWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit the list.
        /// </summary>
        internal static string editList {
            get {
                return ResourceManager.GetString("editList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Floating point parameters.
        /// </summary>
        internal static string FloatRange {
            get {
                return ResourceManager.GetString("FloatRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Floating point parameters.
        /// </summary>
        internal static string floatRangeParams {
            get {
                return ResourceManager.GetString("floatRangeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all floating-point parameter fields are filled in correctly.
        /// </summary>
        internal static string floatRangeValidationError {
            get {
                return ResourceManager.GetString("floatRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forced closure.
        /// </summary>
        internal static string forceCloseButton {
            get {
                return ResourceManager.GetString("forceCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters to select from the list.
        /// </summary>
        internal static string FromList {
            get {
                return ResourceManager.GetString("FromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters to select from the list.
        /// </summary>
        internal static string fromListParams {
            get {
                return ResourceManager.GetString("fromListParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all fields of the parameters selected from the list are filled in correctly.
        /// </summary>
        internal static string fromListValidationError {
            get {
                return ResourceManager.GetString("fromListValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting up the list of parameter elements:.
        /// </summary>
        internal static string fromListValuesEdit {
            get {
                return ResourceManager.GetString("fromListValuesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generate.
        /// </summary>
        internal static string generate {
            get {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gamedata generation.
        /// </summary>
        internal static string generateDialog {
            get {
                return ResourceManager.GetString("generateDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Give the player a knife at the beginning of the game.
        /// </summary>
        internal static string giveKnife {
            get {
                return ResourceManager.GetString("giveKnife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase the respawn frequency of NPCs.
        /// </summary>
        internal static string increaseRespawn {
            get {
                return ResourceManager.GetString("increaseRespawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integer parameters.
        /// </summary>
        internal static string IntRange {
            get {
                return ResourceManager.GetString("IntRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Integer parameters.
        /// </summary>
        internal static string intRangeParams {
            get {
                return ResourceManager.GetString("intRangeParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all fields of integer parameters are filled in correctly.
        /// </summary>
        internal static string intRangeValidationError {
            get {
                return ResourceManager.GetString("intRangeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of items.
        /// </summary>
        internal static string itemsList {
            get {
                return ResourceManager.GetString("itemsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items.
        /// </summary>
        internal static string itemsTab {
            get {
                return ResourceManager.GetString("itemsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuring the generation of item parameters.
        /// </summary>
        internal static string itemsTitle {
            get {
                return ResourceManager.GetString("itemsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items to leave behind when killing NPCs.
        /// </summary>
        internal static string keepDeathItems {
            get {
                return ResourceManager.GetString("keepDeathItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Location.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Simple randomizer for S.T.A.L.K.E.R. Shadow of Chernobyl.
        /// </summary>
        internal static string mainFormName {
            get {
                return ResourceManager.GetString("mainFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum number of artifact stats.
        /// </summary>
        internal static string maxArtefactStats {
            get {
                return ResourceManager.GetString("maxArtefactStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max. quantity.
        /// </summary>
        internal static string maxCount {
            get {
                return ResourceManager.GetString("maxCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max. multiplier.
        /// </summary>
        internal static string maxMultiplier {
            get {
                return ResourceManager.GetString("maxMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max. probability (from 0 to 1).
        /// </summary>
        internal static string maxProbability0to1 {
            get {
                return ResourceManager.GetString("maxProbability0to1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max. value.
        /// </summary>
        internal static string maxValue {
            get {
                return ResourceManager.GetString("maxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Max. number of weapons for a dead NPC to have ammunition.
        /// </summary>
        internal static string maxWeaponToSpawnAmmo {
            get {
                return ResourceManager.GetString("maxWeaponToSpawnAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum number of artifact stats.
        /// </summary>
        internal static string minArtefactStats {
            get {
                return ResourceManager.GetString("minArtefactStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min. quantity.
        /// </summary>
        internal static string minCount {
            get {
                return ResourceManager.GetString("minCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min. multiplier.
        /// </summary>
        internal static string minMultiplier {
            get {
                return ResourceManager.GetString("minMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min. probability (from 0 to 1).
        /// </summary>
        internal static string minProbability0to1 {
            get {
                return ResourceManager.GetString("minProbability0to1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Min. value.
        /// </summary>
        internal static string minValue {
            get {
                return ResourceManager.GetString("minValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The minimum value of the parameter cannot be greater than the maximum.
        /// </summary>
        internal static string minValueCantBeMoreThenMaxValue {
            get {
                return ResourceManager.GetString("minValueCantBeMoreThenMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiplier depending on location.
        /// </summary>
        internal static string multiplierByLevel {
            get {
                return ResourceManager.GetString("multiplierByLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all fields are filled in.
        /// </summary>
        internal static string notAllFieldsComplete {
            get {
                return ResourceManager.GetString("notAllFieldsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all audio file processing streams have been completed.
        /// </summary>
        internal static string notAllSoundThreadsCompleted {
            get {
                return ResourceManager.GetString("notAllSoundThreadsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all texture processing streams have been completed.
        /// </summary>
        internal static string notAllTextureThreadsCompleted {
            get {
                return ResourceManager.GetString("notAllTextureThreadsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional weapons.
        /// </summary>
        internal static string npcAdditionalWeapons {
            get {
                return ResourceManager.GetString("npcAdditionalWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Communities.
        /// </summary>
        internal static string npcCommunities {
            get {
                return ResourceManager.GetString("npcCommunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exceptions.
        /// </summary>
        internal static string npcExceptions {
            get {
                return ResourceManager.GetString("npcExceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand NPC joining camps (breaks some scripts).
        /// </summary>
        internal static string npcExtendCamp {
            get {
                return ResourceManager.GetString("npcExtendCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated names.
        /// </summary>
        internal static string npcGenNames {
            get {
                return ResourceManager.GetString("npcGenNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thumbnails.
        /// </summary>
        internal static string npcIcons {
            get {
                return ResourceManager.GetString("npcIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items that do not need
        ///to be removed from NPCs when generating.
        /// </summary>
        internal static string npcKeepSupplies {
            get {
                return ResourceManager.GetString("npcKeepSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Items that do not need to be removed from NPCs when generating.
        /// </summary>
        internal static string npcKeepSuppliesSingleLine {
            get {
                return ResourceManager.GetString("npcKeepSuppliesSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main weapon.
        /// </summary>
        internal static string npcMainWeapons {
            get {
                return ResourceManager.GetString("npcMainWeapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Models.
        /// </summary>
        internal static string npcModels {
            get {
                return ResourceManager.GetString("npcModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Money.
        /// </summary>
        internal static string npcMoney {
            get {
                return ResourceManager.GetString("npcMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each NPC parameter.
        /// </summary>
        internal static string npcProbability {
            get {
                return ResourceManager.GetString("npcProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rank.
        /// </summary>
        internal static string npcRank {
            get {
                return ResourceManager.GetString("npcRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use one random weapon from both lists.
        /// </summary>
        internal static string npcSingleWeapon {
            get {
                return ResourceManager.GetString("npcSingleWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voice acting.
        /// </summary>
        internal static string npcSounds {
            get {
                return ResourceManager.GetString("npcSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NPCs.
        /// </summary>
        internal static string npcTab {
            get {
                return ResourceManager.GetString("npcTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuring NPC generation.
        /// </summary>
        internal static string npcTitle {
            get {
                return ResourceManager.GetString("npcTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unique names.
        /// </summary>
        internal static string npcUniqueNames {
            get {
                return ResourceManager.GetString("npcUniqueNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number in order.
        /// </summary>
        internal static string numberInOrder {
            get {
                return ResourceManager.GetString("numberInOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The guys from Metacognix write: &quot;The 1.0006 game engine has code changes that cause crashes when weapons, ammo or other items are destroyed while they are still being used...&quot;
        ///And &quot;This error can also happen in mods that change ammo and/or weapons&quot;
        ///
        ///https://www.metacognix.com/stlkrsoc/CrashesStillInTheGame.html
        ///
        ///The error itself looks like this:
        ///
        ///sv reject.id_parent[21043][mil_freedom_respawn_3: mil_freedom_respawn_321043] id_entity[36660][bolt: bolt][137703]
        ///sv reject.id_parent[21043][mil_freedom_r [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string onePointFourAdvertise {
            get {
                return ResourceManager.GetString("onePointFourAdvertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The 1.0004 version of the game is more stable than 1.0006 when manipulating the communities and respawn frequency of NPCs. But why?.
        /// </summary>
        internal static string onePointFourLink {
            get {
                return ResourceManager.GetString("onePointFourLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        internal static string order {
            get {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The specified number already exists in the order.
        /// </summary>
        internal static string orderAlreadyExists {
            get {
                return ResourceManager.GetString("orderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters with several different types of values.
        /// </summary>
        internal static string orderListParams {
            get {
                return ResourceManager.GetString("orderListParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        internal static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter reduction:.
        /// </summary>
        internal static string paramEdit {
            get {
                return ResourceManager.GetString("paramEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rules for generating parameters.
        /// </summary>
        internal static string parameterDialog {
            get {
                return ResourceManager.GetString("parameterDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter name.
        /// </summary>
        internal static string parameterName {
            get {
                return ResourceManager.GetString("parameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path specified for the game sounds does not contain the &apos;sounds&apos; folder.
        /// </summary>
        internal static string pathDoesNotContainsSounds {
            get {
                return ResourceManager.GetString("pathDoesNotContainsSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path specified for the game textures does not contain the folder &apos;textures&apos;.
        /// </summary>
        internal static string pathDoesNotContainsTextures {
            get {
                return ResourceManager.GetString("pathDoesNotContainsTextures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accuracy.
        /// </summary>
        internal static string precision {
            get {
                return ResourceManager.GetString("precision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The accuracy of the parameter value cannot be less than 0.
        /// </summary>
        internal static string precisionCantBeLessThen0 {
            get {
                return ResourceManager.GetString("precisionCantBeLessThen0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Probability depending on the community.
        /// </summary>
        internal static string probabilityByCommunity {
            get {
                return ResourceManager.GetString("probabilityByCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown....
        /// </summary>
        internal static string programClosing {
            get {
                return ResourceManager.GetString("programClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of rain for each weather section.
        /// </summary>
        internal static string rainProbability {
            get {
                return ResourceManager.GetString("rainProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Random probability of each generation.
        /// </summary>
        internal static string randomProbability {
            get {
                return ResourceManager.GetString("randomProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved in .
        /// </summary>
        internal static string savedIn {
            get {
                return ResourceManager.GetString("savedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save gamedata to:.
        /// </summary>
        internal static string saveIn {
            get {
                return ResourceManager.GetString("saveIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The section string contains more than one character &apos;:&apos;.
        /// </summary>
        internal static string sectionStringNotCorrect {
            get {
                return ResourceManager.GetString("sectionStringNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The multiplier of the sale price to the player.
        /// </summary>
        internal static string sellMultiplier {
            get {
                return ResourceManager.GetString("sellMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Multiplier sections for selling prices to the player.
        /// </summary>
        internal static string sellMultiplierSections {
            get {
                return ResourceManager.GetString("sellMultiplierSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters to be shuffled between sections.
        /// </summary>
        internal static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters to be shuffled between sections.
        /// </summary>
        internal static string shuffleParams {
            get {
                return ResourceManager.GetString("shuffleParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shuffle the entire game text.
        /// </summary>
        internal static string shuffleText {
            get {
                return ResourceManager.GetString("shuffleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of shuffling each text block.
        /// </summary>
        internal static string shuffleTextProbability {
            get {
                return ResourceManager.GetString("shuffleTextProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Not all fields of the mixing parameters are filled in correctly.
        /// </summary>
        internal static string shuffleValidationError {
            get {
                return ResourceManager.GetString("shuffleValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path to the sounds folder.
        /// </summary>
        internal static string soudnsPath {
            get {
                return ResourceManager.GetString("soudnsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sounds.
        /// </summary>
        internal static string sounds {
            get {
                return ResourceManager.GetString("sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of mixing each sound.
        /// </summary>
        internal static string soundsProbability {
            get {
                return ResourceManager.GetString("soundsProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The step of rounding the duration of audio files (sec.).
        /// </summary>
        internal static string soundsRound {
            get {
                return ResourceManager.GetString("soundsRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace the sounds of footsteps and rain.
        /// </summary>
        internal static string soundsStepRainReplace {
            get {
                return ResourceManager.GetString("soundsStepRainReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sounds/Textures.
        /// </summary>
        internal static string soundsTexturesTab {
            get {
                return ResourceManager.GetString("soundsTexturesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Setting up mixing of sounds and textures.
        /// </summary>
        internal static string soundsTexturesTitle {
            get {
                return ResourceManager.GetString("soundsTexturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start generating.
        /// </summary>
        internal static string startGenerate {
            get {
                return ResourceManager.GetString("startGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each cache parameter.
        /// </summary>
        internal static string stashesProbability {
            get {
                return ResourceManager.GetString("stashesProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the cache data file.
        /// </summary>
        internal static string stashesReadError {
            get {
                return ResourceManager.GetString("stashesReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stashes.
        /// </summary>
        internal static string stashesTab {
            get {
                return ResourceManager.GetString("stashesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuring cache filling.
        /// </summary>
        internal static string stashesTitle {
            get {
                return ResourceManager.GetString("stashesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Characteristics section.
        /// </summary>
        internal static string statSection {
            get {
                return ResourceManager.GetString("statSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The string has an incorrect format.
        /// </summary>
        internal static string stringHasWrongFormat {
            get {
                return ResourceManager.GetString("stringHasWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Game text.
        /// </summary>
        internal static string textGen {
            get {
                return ResourceManager.GetString("textGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Textures.
        /// </summary>
        internal static string textures {
            get {
                return ResourceManager.GetString("textures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The path to the textures folder.
        /// </summary>
        internal static string texturesPath {
            get {
                return ResourceManager.GetString("texturesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of mixing each texture.
        /// </summary>
        internal static string texturesProbability {
            get {
                return ResourceManager.GetString("texturesProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace interface elements.
        /// </summary>
        internal static string texturesUiReplace {
            get {
                return ResourceManager.GetString("texturesUiReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of threads to process.
        /// </summary>
        internal static string threadsCount {
            get {
                return ResourceManager.GetString("threadsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of thunderstorms for each weather section.
        /// </summary>
        internal static string thunderProbability {
            get {
                return ResourceManager.GetString("thunderProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quantity on sale.
        /// </summary>
        internal static string tradeCount {
            get {
                return ResourceManager.GetString("tradeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of items in the merchant&apos;s assortment: .
        /// </summary>
        internal static string traderItemList {
            get {
                return ResourceManager.GetString("traderItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of being on sale.
        /// </summary>
        internal static string traderItemProbability {
            get {
                return ResourceManager.GetString("traderItemProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating the presence of each item.
        /// </summary>
        internal static string tradersProbability {
            get {
                return ResourceManager.GetString("tradersProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to upload merchant&apos;s configuration file:.
        /// </summary>
        internal static string tradersReadError {
            get {
                return ResourceManager.GetString("tradersReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The range of merchants.
        /// </summary>
        internal static string tradersTab {
            get {
                return ResourceManager.GetString("tradersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Merchant assortment generation settings.
        /// </summary>
        internal static string tradersTitle {
            get {
                return ResourceManager.GetString("tradersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In a nutshell: I do not know, but....
        /// </summary>
        internal static string twoWords {
            get {
                return ResourceManager.GetString("twoWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock Sidorovich&apos;s door.
        /// </summary>
        internal static string unlockTraderDoor {
            get {
                return ResourceManager.GetString("unlockTraderDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Used cartridges.
        /// </summary>
        internal static string useAmmo {
            get {
                return ResourceManager.GetString("useAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number of values.
        /// </summary>
        internal static string valueCount {
            get {
                return ResourceManager.GetString("valueCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List of values.
        /// </summary>
        internal static string valueList {
            get {
                return ResourceManager.GetString("valueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value type.
        /// </summary>
        internal static string valueType {
            get {
                return ResourceManager.GetString("valueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All lines must have the name of the weapon and at least one type of ammunition.
        /// </summary>
        internal static string weaponAmmoValidation {
            get {
                return ResourceManager.GetString("weaponAmmoValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weapons.
        /// </summary>
        internal static string weapons {
            get {
                return ResourceManager.GetString("weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated weapon parameters.
        /// </summary>
        internal static string weaponsParams {
            get {
                return ResourceManager.GetString("weaponsParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weapon parameters.
        /// </summary>
        internal static string weaponsParamsShort {
            get {
                return ResourceManager.GetString("weaponsParamsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each parameter of the weapon.
        /// </summary>
        internal static string weaponsProbability {
            get {
                return ResourceManager.GetString("weaponsProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the weapon data file:.
        /// </summary>
        internal static string weaponsReadError {
            get {
                return ResourceManager.GetString("weaponsReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating weapon parameters.
        /// </summary>
        internal static string weaponsSections {
            get {
                return ResourceManager.GetString("weaponsSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weapon sections.
        /// </summary>
        internal static string weaponsSectionsShort {
            get {
                return ResourceManager.GetString("weaponsSectionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuring the generation of weapon and ammo parameters.
        /// </summary>
        internal static string weaponsTitle {
            get {
                return ResourceManager.GetString("weaponsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated parameters.
        /// </summary>
        internal static string weatherParams {
            get {
                return ResourceManager.GetString("weatherParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameters for weather generation.
        /// </summary>
        internal static string weatherParamsFull {
            get {
                return ResourceManager.GetString("weatherParamsFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The probability of generating each weather parameter.
        /// </summary>
        internal static string weatherProbability {
            get {
                return ResourceManager.GetString("weatherProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error reading the weather data file:.
        /// </summary>
        internal static string weatherReadError {
            get {
                return ResourceManager.GetString("weatherReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sections for generating parameters.
        /// </summary>
        internal static string weatherSections {
            get {
                return ResourceManager.GetString("weatherSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weather sections.
        /// </summary>
        internal static string weatherSectionsShort {
            get {
                return ResourceManager.GetString("weatherSectionsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Weather.
        /// </summary>
        internal static string weatherTab {
            get {
                return ResourceManager.GetString("weatherTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configuring the generation of weather parameters.
        /// </summary>
        internal static string weatherTitle {
            get {
                return ResourceManager.GetString("weatherTitle", resourceCulture);
            }
        }
    }
}
